name: Ingest Microsoft PowerToys Public Repo Data into Port

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow on a schedule (e.g., every 6 hours)
  schedule:
    - cron: '0 */6 * * *' # You can adjust the schedule as needed

jobs:
  ingest-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Use a specific version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ingestion Script
        env:
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python scripts/ingest_public_repo_data.py
